from django.urls import include, path
from . import views

app_name = 'adminn'

urlpatterns = [
    path('adminhome/',views.adminhome, name='adminhome'),
    path('signout/',views.signout, name='signout'),
    path('users/', views.users, name='users'),
    path('blockuser/<int:user_id>/', views.blockuser, name='blockuser'),
    path('unblockuser/<int:user_id>/', views.unblockuser, name='unblockuser'),
    path('categorylist/', views.categorylist, name='categorylist'),
    path('productlist/', views.productlist, name='productlist'),
    path('addproduct/', views.addproduct, name='addproduct'),
    path('editproduct/<int:product_id>/', views.editproduct, name = 'editproduct'),
    path('deleteproduct/<int:product_id>/', views.deleteproduct, name = 'deleteproduct'),
    path('restore-product/<int:product_id>/', views.restore_product, name='restore_product'),
    path('permanent-delete-product/<int:product_id>/', views.permanent_delete_product, name='permanent_delete_product'),
    path('delete-product-image/<int:image_id>/', views.delete_product_image, name='delete_product_image'),
    path('addcategory/', views.addcategory, name='addcategory'),
    path('editcategory/<int:category_id>/', views.editcategory, name='editcategory'),
    path('deletecategory/<int:category_id>/', views.deletecategory, name='deletecategory'),
    path('restore-category/<int:category_id>/', views.restore_category, name='restore_category'),
    path('permanent-delete-category/<int:category_id>/', views.permanent_delete_category, name='permanent_delete_category'),
    path('coupons/', views.admin_coupon_list, name='admin_coupon_list'),
    path('coupons/add/', views.admin_add_coupon, name='admin_add_coupon'),
    path('coupons/<int:coupon_id>/edit/', views.admin_edit_coupon, name='admin_edit_coupon'),
    path('coupons/<int:coupon_id>/toggle/', views.admin_toggle_coupon, name='admin_toggle_coupon'),
    path('coupons/<int:coupon_id>/usage/', views.admin_coupon_usage, name='admin_coupon_usage'),
    path('orders/', views.admin_orders, name='admin_orders'),
    path('orders/<int:order_id>/update/', views.update_order_status, name='update_order_status'),
    
    path('orders/<int:order_id>/', views.admin_order_detail, name='admin_order_detail'),
    path('orders/<int:order_id>/download-invoice/', views.download_invoice, name='download_invoice'),
    path('orders/<int:order_id>/send-invoice/', views.send_invoice, name='send_invoice'),
    path('sales-report/', views.sales_report, name='sales_report'),
    path('process-refund/<int:order_id>/', views.process_refund, name='process_refund'),
    path('offers/', views.offers_dashboard, name='offers_dashboard'),
    path('offers/product/add/', views.add_product_offer, name='add_product_offer'),
    path('offers/product/edit/<int:offer_id>/', views.edit_product_offer, name='edit_product_offer'),
    path('offers/product/delete/<int:offer_id>/', views.delete_product_offer, name='delete_product_offer'),
    path('offers/product/toggle/<int:offer_id>/', views.toggle_product_offer, name='toggle_product_offer'),
    path('offers/category/add/', views.add_category_offer, name='add_category_offer'),
    path('offers/category/edit/<int:offer_id>/', views.edit_category_offer, name='edit_category_offer'),
    path('offers/category/delete/<int:offer_id>/', views.delete_category_offer, name='delete_category_offer'),
    path('offers/category/toggle/<int:offer_id>/', views.toggle_category_offer, name='toggle_category_offer'),
    path('delivery-charges/', views.delivery_charge_list, name='delivery_charge_list'),
    path('add-delivery-charge/', views.add_delivery_charge, name='add_delivery_charge'),
    path('edit-delivery-charge/<int:charge_id>/', views.edit_delivery_charge, name='edit_delivery_charge'),
    path('deactivate-delivery-charge/<int:charge_id>/', views.deactivate_delivery_charge, name='deactivate_delivery_charge'),
    path('activate-delivery-charge/<int:charge_id>/', views.activate_delivery_charge, name='activate_delivery_charge'),
    path('delete-delivery-charge/<int:charge_id>/', views.delete_delivery_charge, name='delete_delivery_charge'),
]