# Generated by Django 5.1.5 on 2025-02-05 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_images_alter_productimage_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
    ]
