# Generated by Django 5.1.5 on 2025-02-12 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_product_max_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='max_quantity',
        ),
    ]
