# Generated by Django 5.1.5 on 2025-03-21 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
