# Generated by Django 5.1.5 on 2025-03-05 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_category_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_deleted'], name='category_ca_is_dele_19b592_idx'),
        ),
    ]
