# Generated by Django 5.1.5 on 2025-03-19 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_coupon_order_discount_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='discount_amount',
            field=models.FloatField(),
        ),
    ]
