# Generated by Django 5.1.5 on 2025-04-07 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_order_refund_reason_order_refund_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_discount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount_amount',
            field=models.FloatField(default=0),
        ),
    ]
